
[project]
license = "Apache-2.0"
org-name = "wso2"
version = "0.0.1"
authors = ["Saskiya"]
repository = "https://github.com/wso2-ballerina/package-twilio"
keywords = ["twilio", "sms", "call", "otp"]
